name: Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  minio-4-testing:

    name: MinIO 4 Testing
    runs-on: [ ubuntu-latest ]

    steps:

      - name: Build on ${{ matrix.os }}
        run: |
          # Download MinIO
          wget https://dl.min.io/server/minio/release/linux-amd64/minio
          chmod +x minio
          mv minio /usr/local/bin/minio
          minio
          echo "The idea is to build minio image from downloaded repository";
