name: Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  minio-4-testing:

    name: MinIO 4 Testing
    runs-on: [ ubuntu-latest ]

    steps:

      - name: Download the repository
        uses: actions/checkout@v2

      - name: Execute MinIO
        run: |
          "${GITHUB_WORKSPACE}/bash-scripts/deploy-minio.sh"

      - name: Execute Python SDK
        run: |
          python3 "${GITHUB_WORKSPACE}/python-scripts/test-image.py"
